name: Scala CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create version
      run: echo "BUILD_VERSION=$(grep version package.json | cut -c 15- | rev | cut -c 3- | rev)-dev.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: VERSION=${{ env.BUILD_VERSION }}
        tags: |
          pwierucki/tutomy-frontend:latest
          pwierucki/tutomy-frontend:${{ env.BUILD_VERSION }}


